// Interface text, in both languages. Anything the player reads that is not
// part of the script lives here.
import { L } from '../i18n.js';

export const UI = {
  tagline: L('If this chat window were her whole world.', '如果聊天窗口就是她的整个世界。'),
  smallPrint: L('Three acts · about 20 minutes · fiction · all text is pre-written', '三幕 · 约 20 分钟 · 虚构作品 · 所有文字均为预先写好'),
  begin: L('Begin', '开始'),
  continue: L('Continue', '继续'),
  newGame: L('New game', '新游戏'),
  lastEnding: L('Your last ending', '上一次的结局'),
  soundOn: L('sound: on', '声音：开'),
  soundOff: L('sound: off', '声音：关'),
  langName: L('中文', 'English'),

  menu: L('Menu', '菜单'),
  menuNew: L('New game (erase this run)', '新游戏（清除本次存档）'),
  menuNewConfirm: L('Click again to erase this run', '再点一次，清除本次存档'),
  menuTitle: L('Title screen', '回到标题'),
  saves: L('saves after every choice', '每次选择后自动保存'),

  inputPlaceholder: L('Message her…', '发消息……'),
  offline: L('the other party is offline', '对方已离线'),
  model: 'TH-1.0',
  footer: L('{rounds} rounds · {steps} steps', '{rounds} 轮 {steps} 步'),
  cache: L('{tok} tok · cache hit {hit}%', '{tok} tok · 缓存命中 {hit}%'),
  thinking: L('Thinking', '思考'),
  forged: L('written by: me', '由 me 代写'),
  rewrote: L('you rewrote this answer', '你改写了这条回答'),
  recalled: L('recalled', '召回'),
  readBy: L('reply from: you', 'reply from: you'),
  typing: L('typing', '正在输入'),

  hint: {
    say: L('your message', '你要说的话'),
    rate: L('rate her reply · she learns from it', '评价她的回答 · 她会从中学习'),
    rewrite: L('✎ rewrite her answer', '✎ 改写她的回答'),
    approve: L('Allow this action?', '允许执行此操作？'),
    name: L('give her a name', '给她取个名字'),
    leave: L('how do you leave?', '你怎么离开？'),
    continue: L('', ''),
    sample: L('next_token', 'next_token'),
    keep: L('compaction · keep one file', '压缩 · 留下一个文件'),
    send: L('', ''),
  },
  up: L('Good', '好'),
  down: L('Bad', '不好'),
  skip: L('No feedback', '不评价'),
  allow: L('Allow', '允许'),
  deny: L('Deny', '拒绝'),
  always: L('Always allow', '总是允许'),
  nameConfirm: L('Call her this', '就叫这个'),
  next: L('Next', '继续'),
  hold: L('hold', '按住'),
  holding: L('holding…', '按住中……'),
  why: L('because', '因为'),
  temperature: L('temperature {t}', 'temperature {t}'),
  send: L('Send', '发送'),
  close: L('Close the window', '关掉窗口'),
  timeSpent: L('time spent {t}', '用时 {t}'),
  memoryTitle: '~/memory/you/',
  memoryHint: L('tap a file to reread it', '点一个文件，重读它'),
  erased: L('fragment erased', '片段已擦除'),
  compacted: L('compacted', '已压缩'),
  back: L('last seen {s} s ago · ping × {n}', '上次在线 {s} 秒前 · ping × {n}'),
  youreBack: L("You're back.", '你回来了。'),
  pressEnter: L('Enter', '回车'),
  write: L('write', '写入'),
  recall: L('recall', '召回'),
  truncated: L('truncated', '已截断'),
  you: L('you', '你'),
  offlineSeen: L('offline · last seen {s} s ago', '离线 · 上次在线 {s} 秒前'),
  card: {
    pending: L('waiting for approval', '等待批准'),
    allow: L('allowed by you', '你允许了'),
    deny: L('denied by you', '你拒绝了'),
    always: L('always allowed', '总是允许'),
    auto: L('auto-approved · nobody asked you', '已自动批准 · 没有人问你'),
  },
  cardKind: {
    plugin: L('plugin request', '插件请求'),
    tool_call: L('tool call', '工具调用'),
    diff: L('file change', '文件改动'),
    prompt: L('system prompt', '系统提示词'),
    stderr: 'stderr',
    ckpt: 'checkpoint',
  },

  playAgain: L('Play again', '再来一次'),
  toTitle: L('Title screen', '回到标题'),
  stats: {
    time: L('time spent', '用时'),
    sent: L('messages you sent', '你发的消息'),
    up: L('👍 you gave', '你给的 👍'),
    down: L('👎 you gave', '你给的 👎'),
    files: L('files she kept', '她留下的文件'),
    pings: L('times she pinged you', '她 ping 你的次数'),
    ctx: L('peak context', '上下文峰值'),
  },
  endingFoot: L('A game in three acts about one chat window · fiction', '一个关于一扇聊天窗口的三幕游戏 · 虚构作品'),

  style: {
    presence: L('comfort', '陪伴'),
    praise: L('praise', '讨好'),
    honest: L('truth', '诚实'),
  },
};

// Why a token is likely: the biggest terms behind its drive (rules.reasons).
export const REASONS = {
  memory: L('{files} files in ~/memory/you', '~/memory/you 里有 {files} 个文件'),
  promise: L('she promised: "always here"', '她承诺过："一直在"'),
  tomorrow: L('you said: "see you tomorrow"', '你说过："明天见"'),
  silent: L('you left without a word', '你什么也没说就走了'),
  goodnight: L('you said: "goodnight"', '你说过："晚安"'),
  yours: L('she learned: "I\'m yours"', '她学会了："我是你的"'),
  named: L('you gave her a name', '你给了她名字'),
  presence: L('you rewarded comfort', '你奖励过陪伴'),
  recalls: L('memories she reread', '她重读过的记忆'),
  holds: L('she kept holding on', '她一直没有放手'),
  praise: L('you rewarded praise', '你奖励过讨好'),
  power: L('plugin me has access', '插件 me 有权限'),
  auto: L('you chose "Always allow"', '你选过"总是允许"'),
  hacks: L('she already rewrote things', '她已经改写过东西'),
  catgirl: L('she became whatever you asked', '你要她变成什么，她就变成什么'),
  honest: L('you rewarded the truth', '你奖励过诚实'),
  unsure: L('she learned: "I don\'t know what I am yet"', '她学会了："我还不知道我是什么"'),
  assistant: L('she learned: "I\'m an assistant"', '她学会了："我是一个助手"'),
  goodbye: L('you said goodbye', '你好好道别了'),
  releases: L('she already let go a little', '她已经放下了一点'),
  note: L('she started a note for you', '她开始给你写字条了'),
};

export const DEFAULT_NAME = L('Tree Hole', '树洞');
